openapi: 3.0.3
info:
  title: ToDo with Authentication & Swagger
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /todos:
    get:
      summary: Get a list of todos
      operationId: getTodos
      security:
        - BearerAuth: []
      responses:
        '200':
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ToDo'
        '401':
          $ref: '#/components/responses/Unauthorized'
    post:
      summary: Create a new todo
      operationId: createTodo
      security:
        - BearerAuth: []
      requestBody:
        description: The todo to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDoCreate'
      responses:
        '201':
          description: The created todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /todos/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: The ID of the todo to retrieve, update, or delete
        schema:
          type: integer
    get:
      summary: Get a todo by ID
      operationId: getTodoById
      security:
        - BearerAuth: []
      responses:
        '200':
          description: The todo with the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Update a todo by ID
      operationId: updateTodoById
      security:
        - BearerAuth: []
      requestBody:
        description: The updated todo data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDoCreate'
      responses:
        '200':
          description: The updated todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete a todo by ID
      operationId: deleteTodoById
      security:
        - BearerAuth: []
      responses:
        '204':
          description: The todo was successfully deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    ToDo:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the todo
        title:
          type: string
          description: The title of the todo
        body:
          type: string
          description: The description of the todo
        is_active:
          type: boolean
          description: The active status of the todo
      required:
        - id
        - title
        - is_active
    ToDoCreate:
      type: object
      properties:
        title:
          type: string
          description: The title of the todo
        body:
          type: string
          description: The description of the todo
        is_active:
          type: boolean
          description: The active status of the todo
      required:
        - title
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    BadRequest:
      description: Invalid request body or parameters
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: A description of the error
            required:
              - message
    Unauthorized:
      description: Authentication credentials were missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: A description of the error
            required:
              - message
    NotFound:
      description: Record not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: A description of the error
            required:
              - message
